### ISSUE TITLE
Error when using globals

### ISSUE THREAD

**Issue by euoia** [eminos/statamic-iconify#1]
I created a global set for my icons, but when I attempt to use this fantastic plugin, I get an error:

```
<a href="{{ my_business.map_link }}" target="_blank"
    >Map {{ iconify:decorations.map_icon }}
</a>
```

Call to a member function raw() on array

The error seems to be here:
https://github.com/eminos/statamic-iconify/blob/main/src/Tags/IconifyTag.php#L23

**Comment by eminos** [comment]
Yep. It wasn't working when using the fieldtype in a Global.
Thanks for reporting.
Fixed in v1.1.0 👍
